name: stix
description: "Ollama Flutter Client"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  go_router: ^14.7.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.273

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - .env